/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '副本': typeof import('./src/components/Record - 副本.vue')['default']
    AiImg: typeof import('./src/components/guankong/AiImg.vue')['default']
    AnquanPop: typeof import('./src/components/AnquanPop.vue')['default']
    DamTree: typeof import('./src/components/DamTree.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElectricHole: typeof import('./src/components/ElectricHole.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Environment: typeof import('./src/components/guankong/Environment.vue')['default']
    EnvironmentPop: typeof import('./src/components/EnvironmentPop.vue')['default']
    EquipmentPositioning: typeof import('./src/components/Right/Components/EquipmentPositioning.vue')['default']
    FullScreenAdapter: typeof import('./src/components/FullScreenAdapter.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Machinery: typeof import('./src/components/guankong/Machinery.vue')['default']
    MachineryContent: typeof import('./src/components/Right/Components/MachineryContent.vue')['default']
    MvPop: typeof import('./src/components/guankong/MvPop.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Overview: typeof import('./src/components/guankong/Overview.vue')['default']
    People: typeof import('./src/components/guankong/People.vue')['default']
    PersonContent: typeof import('./src/components/Right/Components/PersonContent.vue')['default']
    'Record - 副本': typeof import('./src/components/Record - 副本.vue')['default']
    Right: typeof import('./src/components/Right/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeAxle: typeof import('./src/components/guankong/TimeAxle.vue')['default']
    TimeSlider: typeof import('./src/components/guankong/TimeSlider.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
    VideoContent: typeof import('./src/components/Right/Components/VideoContent.vue')['default']
    VideoPop: typeof import('./src/components/VideoPop.vue')['default']
    VideoTime: typeof import('./src/components/guankong/VideoTime.vue')['default']
  }
}
